@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gradientmod.gradient.entities;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
